### ISSUE TITLE
Can't load firebase.json or caller does not have permission

### ISSUE THREAD

**Issue by MattBuilt1** [sws2apps/firebase-deployment#77]
I started with the usage example and would get a warning "Did you forget to use actions/checkout before this step?".  Then, after credentials file was created, the first error would be "could not load config file firebase.json".  The firebase.json file is in the root of the project.  Then I added the actions/checkout@v2 step and the warning went away.  However, now the error says that the caller does not have permission.  My latest yml file is:
```
name: Deploy to Firebase

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: sws2apps/firebase-deployment@main #consider using pin for dependabot auto update
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          config: 'firebase.json'
          project: 'stamps-microservice' #required
```
I did create the Workload Identity Pool with a provider connected service account.  I appreciate any insight into how to find my error.
